version: '3.0'
services:
  mysqldb:
    # platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    # env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: Madhav@19
      MYSQL_DATABASE: memorygame
      MYSQL_TCP_PORT: 3306

    ports:
      - 3307:3306   #Host:Container 
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
                # condition: service_healthy
    # command: [./waitforit.sh"]
    build: ./
    restart: unless-stopped
    # env_file: ./.env
    ports:
      - 7001:7000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=Madhav@19
      - DB_NAME=memorygame
      - DB_PORT=3306
    stdin_open: true
    tty: true
volumes: 
  db:
    driver: local