version: '3.0'
services:
  mysqldb:
    image: mysql:5.7
    # restart: unless-stopped
    # env_file: ./.env
    environment:
      - MYSQL_USER=sampleuser
      - MYSQL_USER_PASSWORD=Game@123
      - MYSQL_DATABASE=memorygame
    ports:
      - 3307:3306   #Host:Container 
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    # env_file: ./.env
    ports:
      - 7001:7000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=sampleuser
      - DB_PASSWORD=Game@123
      - DB_NAME=memorygame
      - DB_PORT=3306
    stdin_open: true
    tty: true
volumes: 
  db:
    driver: local